version: '3.6'

networks:
  app-tier:
    driver: bridge

services: 
   londontasmaserver:
    hostname: 'londontasmaserver'
    ports:      
      - "3636:3636"       
    networks:
      - app-tier
