version: '3.6'

networks:
  app-tier:
    driver: bridge

services: 
   londontasmaserver:
    build:
      context: .
      dockerfile: 'build/Dockerfile'
    container_name: 'londontasmaserver'
    hostname: 'londontasmaserver'
    ports:      
      - "3636:3636"
      - "3635:3635"  
      - "3634:3634" 
    networks:
      - app-tier
