log:
  consoleEnable: true
  fileEnable: true
  printAsJson: false
  logLevel: "DEBUG"
  logDirectory: "./logs/"
  logFile: "jt808-server-go.log"
  maxSizeOfRolling: 50
  maxBackupsOfRolling: 128
  maxAgeOfRolling: 7

server:
  name: "jt808-server-go"
  port:
    tcpPort: "3636"
    udpPort: "3635"
    httpPort: "3634"
  banner:
    enable: true
    bannerPath: "configs/banner.txt"
